// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7J47vzvzUnAp015DeHhMsBhEs68eDjWw',
    appId: '1:375733449982:web:c54f802d4860a7e9a061af',
    messagingSenderId: '375733449982',
    projectId: 'vertretung-b5742',
    authDomain: 'vertretung-b5742.firebaseapp.com',
    databaseURL: 'https://vertretung-b5742.firebaseio.com',
    storageBucket: 'vertretung-b5742.appspot.com',
    measurementId: 'G-GL8RZ5JJP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFexN4pWnz04vYvtRfoo3k2xWJ__y_xh0',
    appId: '1:375733449982:android:d5ee95a7bc5d10a8a061af',
    messagingSenderId: '375733449982',
    projectId: 'vertretung-b5742',
    databaseURL: 'https://vertretung-b5742.firebaseio.com',
    storageBucket: 'vertretung-b5742.appspot.com',
  );
}
